language: node_js
node_js:
  - "stable"
before_script:
  - npm install jscoverage coveralls grunt-cli
after_script:
  - ./node_modules/.bin/jscoverage lib && GRUNTO_COV=1 ./node_modules/.bin/nodeunit --reporter=lcov tests/ | ./node_modules/.bin/coveralls
notifications:
  email:
    on_success: never
    on_failure: always
